[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
tictactoe = "CKkkguDzG9hyiAHDwkB3qw8wT2pgBUwuQtcuwUqAPD2V"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/pratham/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
